ARG BASE_IMAGE=fishbot_base:latest
FROM ${BASE_IMAGE}
SHELL ["/bin/bash", "-c"]

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY

ENV http_proxy=${HTTP_PROXY}
ENV https_proxy=${HTTPS_PROXY}
ENV no_proxy=${NO_PROXY}

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ros-humble-ros-gz-sim \
        ros-humble-ros-gz-bridge \
        ros-humble-ros-gz-image \
        ros-humble-rqt \
        ros-humble-rqt-common-plugins \
        ros-humble-rqt-tf-tree \
        mesa-utils \
        vulkan-tools

# DO NOT CLEAR THE `rm -rf /var/lib/apt/lists/*`
# it leads to the errors in rosdep install

WORKDIR /fishbot_ws

COPY src/gazebo_sim/package.xml src/gazebo_sim/

RUN rosdep update \
    && rosdep install --rosdistro humble --from-paths src --ignore-src -y

COPY src/gazebo_sim/ src/gazebo_sim/

RUN source /opt/ros/humble/setup.bash \
    && colcon build --merge-install --symlink-install \
        --packages-select gazebo_sim

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Source ROS and workspace by default
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
RUN echo "source /fishbot_ws/install/setup.bash" >> ~/.bashrc

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
